import { useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { Account, Balance, formatMinor } from "../../api";
import { FeedbackMessage } from "../feedback/FeedbackMessage";

function accountName(account: Account, index: number): string { return account.display_name || (index === 0 ? "Cuenta principal" : `Cuenta corriente ${index + 1}`); }
function maskAccount(id: string): string { return id.length > 10 ? `${id.slice(0, 4)}••••${id.slice(-4)}` : id; }

interface Props { accounts: Account[]; accountBalances: Record<string, Balance>; activeAccount: Account | null; busy: boolean; renameBusyId: string; notice: string; onSelect: (id: string) => void; onCreate: () => void; onRename: (id: string, name: string) => void; }

/** Compact account card used by the dashboard home. Account actions stay in this card. */
export function AccountList({ accounts, accountBalances, activeAccount, busy, renameBusyId, notice, onSelect, onCreate, onRename }: Props) {
  const [showNumbers, setShowNumbers] = useState(false);
  const [editingId, setEditingId] = useState("");
  const [editingName, setEditingName] = useState("");
  const totalBalance = accounts.reduce((total, account) => { try { return total + BigInt(accountBalances[account.id]?.available_balance ?? "0"); } catch { return total; } }, 0n).toString();

  return <View className="rounded-3xl border border-[#d9e4ed] bg-white p-4 shadow-sm dark:border-[#2d456e] dark:bg-[#1b2a55]">
    <View className="mb-2 flex-row items-center justify-between"><View><Text className="text-base font-bold text-[#24315e] dark:text-[#f6f8fc]">Mis cuentas</Text><Text className="mt-1 text-[10px] text-slate-400 dark:text-[#9fb0c5]">{accounts.length} activas</Text></View><Pressable accessibilityLabel={showNumbers ? "Ocultar numeros de cuenta" : "Mostrar numeros de cuenta"} className="h-9 w-9 items-center justify-center rounded-full bg-[#eef3f8] dark:bg-[#243b68]" onPress={() => setShowNumbers((current) => !current)}><Text className="text-base text-[#2d73a5] dark:text-[#dce8ff]">{showNumbers ? "◉" : "◌"}</Text></Pressable></View>
    {accounts.map((item, index) => { const selected = item.id === activeAccount?.id; const itemBalance = accountBalances[item.id]; return <View className="border-t border-[#d9e4ed] dark:border-[#304979]" key={item.id}><View className={`flex-row items-center ${selected ? "rounded-xl bg-[#edf8fb] dark:bg-[#243b68]" : ""}`}><Pressable className="min-w-0 flex-1 flex-row items-center justify-between py-3" onPress={() => onSelect(item.id)}><View className="min-w-0 flex-1"><Text className="text-xs font-bold text-[#24315e] dark:text-[#f6f8fc]" numberOfLines={1}>{accountName(item, index)}</Text><Text className="mt-1 text-[10px] text-slate-400 dark:text-[#9fb0c5]" numberOfLines={1}>{showNumbers ? item.id : maskAccount(item.id)}</Text></View><Text className="ml-2 text-xs font-bold text-[#24315e] dark:text-[#f6f8fc]">{itemBalance ? formatMinor(itemBalance.available_balance).replace("USD", "B/.") : "—"}</Text></Pressable><Pressable accessibilityLabel={`Editar ${accountName(item, index)}`} className="px-2 py-3" onPress={() => { setEditingId(item.id); setEditingName(accountName(item, index)); }}><Text className="text-lg font-bold text-[#2d73a5] dark:text-[#9fc8ff]">⋯</Text></Pressable></View>{editingId === item.id ? <View className="mb-2 rounded-2xl bg-[#f3f8fb] p-3 dark:bg-[#243b68]"><Text className="mb-2 text-[10px] font-bold text-slate-500 dark:text-[#c0cde4]">Nombre de la cuenta</Text><TextInput className="rounded-xl bg-white px-3 py-3 text-sm dark:bg-[#17264b] dark:text-white" value={editingName} onChangeText={setEditingName} maxLength={48} placeholder="Nombre de cuenta" placeholderTextColor="#9fb0c5" /><View className="mt-2 flex-row justify-end gap-2"><Pressable className="rounded-full bg-slate-100 px-3 py-2 dark:bg-[#304979]" onPress={() => setEditingId("")}><Text className="text-xs font-bold text-slate-600 dark:text-slate-200">Cancelar</Text></Pressable><Pressable className="rounded-full bg-[#14c7bc] px-3 py-2" disabled={renameBusyId === item.id} onPress={() => { onRename(item.id, editingName); setEditingId(""); }}><Text className="text-xs font-bold text-[#24315e]">{renameBusyId === item.id ? "Guardando..." : "Guardar"}</Text></Pressable></View></View> : null}</View>; })}
    <Pressable className="mt-2 flex-row items-center rounded-2xl bg-[#e5f5f7] px-4 py-3 dark:bg-[#243b68]" disabled={busy} onPress={onCreate}><Text className="mr-2 text-xl font-bold text-[#14a9aa]">+</Text><Text className="text-xs font-bold text-[#2d73a5] dark:text-[#dce8ff]">{busy ? "Abriendo cuenta..." : "Abrir nueva cuenta"}</Text></Pressable>
    <View className="mt-3 flex-row items-center justify-between border-t border-[#d9e4ed] pt-3 dark:border-[#304979]"><Text className="text-[10px] text-slate-500 dark:text-[#9fb0c5]">Total de cuentas</Text><Text className="text-xs font-bold text-[#24315e] dark:text-[#f6f8fc]">{accounts.length ? formatMinor(totalBalance).replace("USD", "B/.") : "—"}</Text></View>
    {notice ? <FeedbackMessage tone={notice.includes("lista") || notice.includes("actualizado") ? "success" : "error"} message={notice} /> : null}
  </View>;
}
