import { Pressable, Text, View } from "react-native";
import { useState } from "react";
import { History, Transaction, formatMinor } from "../../api";
import { TransactionChart } from "./TransactionChart";

interface Props { history: History | null; page: number; busy: boolean; onPrevious: () => void; onNext: () => void; }

export function HistoryPanel({ history, page, busy, onPrevious, onNext }: Props) {
  const items = history?.items ?? [];
  const [filter, setFilter] = useState<"all" | "deposit" | "withdrawal" | "transfer">("all");
  const filteredItems = items.filter((item) => filter === "all" || item.type === filter);
  return <View className="rounded-3xl bg-white p-4 dark:bg-[#142235]"><View className="flex-row items-start justify-between"><View><Text className="text-xs font-bold uppercase tracking-[2px] text-slate-400">Consultas</Text><Text className="mt-1 text-xl font-semibold text-[#2d73a5] dark:text-[#7bc7ec]">Historial de transacciones</Text></View><Text className="text-xs text-slate-400">5 por página</Text></View><View className="mt-4 flex-row flex-wrap gap-2">{(["all", "deposit", "withdrawal", "transfer"] as const).map((item) => <Pressable className={`rounded-full px-3 py-2 ${filter === item ? "bg-[#2d73a5]" : "bg-slate-100 dark:bg-[#1d3047]"}`} key={item} onPress={() => setFilter(item)}><Text className={`text-[10px] font-bold ${filter === item ? "text-white" : "text-slate-500 dark:text-slate-300"}`}>{item === "all" ? "Todos" : item === "deposit" ? "Depósitos" : item === "withdrawal" ? "Retiros" : "Transferencias"}</Text></Pressable>)}</View>{filteredItems.length ? <View className="mt-4">{filteredItems.map((item) => <TransactionRow item={item} key={`${item.transfer_id}-${item.created_at}`} />)}</View> : <Text className="mt-5 rounded-2xl bg-slate-50 p-5 text-center text-sm text-slate-500 dark:bg-[#1d3047] dark:text-slate-300">{items.length ? "No hay movimientos con este filtro." : "Todavía no hay movimientos en esta cuenta."}</Text>}<View className="mt-4 flex-row items-center justify-between border-t border-slate-100 pt-4 dark:border-slate-700"><Text className="text-xs text-slate-500 dark:text-slate-300">Página {page}</Text><View className="flex-row gap-2"><Pressable className="rounded-full bg-slate-100 px-4 py-2 dark:bg-[#1d3047]" disabled={page <= 1 || busy} onPress={onPrevious}><Text className="text-xs font-bold text-[#2d73a5] dark:text-[#7bc7ec]">Anterior</Text></Pressable><Pressable className="rounded-full bg-slate-100 px-4 py-2 dark:bg-[#1d3047]" disabled={!history?.has_more || busy} onPress={onNext}><Text className="text-xs font-bold text-[#2d73a5] dark:text-[#7bc7ec]">{busy ? "Cargando…" : "Siguiente"}</Text></Pressable></View></View><TransactionChart transactions={filteredItems} /></View>;
}

function TransactionRow({ item }: { item: Transaction }) { const label = item.type === "deposit" ? "Depósito" : item.type === "withdrawal" ? "Retiro" : item.direction === "credit" ? "Transferencia recibida" : "Transferencia enviada"; return <View className="flex-row items-center justify-between border-b border-slate-100 py-4"><View className="flex-1"><Text className="font-semibold text-[#2d73a5]">{label}</Text><Text className="mt-1 text-xs text-slate-400">{new Date(item.created_at).toLocaleString("es-PA")}</Text></View><Text className={`font-semibold ${item.direction === "credit" ? "text-[#16a89e]" : "text-[#5b20a3]"}`}>{item.direction === "credit" ? "+" : "−"}{formatMinor(item.amount)}</Text></View>; }
